version: '3.8'

services:
  redis:
    image: redis
    env_file: ./.env
    ports:
      - $REDIS_DOCKER_PORT:$REDIS_DOCKER_PORT
    
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
  
  app:
    depends_on:
      - mysqldb
    links:
      - mysqldb
    build: .
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT